export const PARAM_TO_HIGHLIGHT: Record<string, string> = {
  'artilharia': 'artillery',
  'melhor-jogador-fora': 'best-away-player',
  'melhor-banco': 'best-bench',
  'melhor-tecnico': 'best-coach',
  'melhor-jogador-em-casa': 'best-home-player',
  'eficiencia-defensiva': 'defense-efficiency',
  'eficiencia-de-finalizacao': 'finish-efficiency',
  'maior-media': 'highest-average',
  'maior-pontuacao': 'highest-scorer',
  'mais-finalizacoes': 'highest-finisher',
  'menos-valorizado': 'least-valued-player',
  'escalacoes-por-clube': 'lineups-per-club',
  'mais-assistencias': 'more-assists',
  'mais-defesas': 'more-defenses',
  'mais-cartoes-vermelhos': 'more-red-cards',
  'mais-desarmes': 'more-tackles',
  'mais-cartoes-amarelos': 'more-yellow-cards',
  'mais-impedido': 'most-offsided-player',
  'mais-rodadas-como-capitao': 'most-rounds-as-captain',
  'mais-escalado': 'most-scheduled-player',
  'mais-valorizado': 'most-valued-player',
  'pontos-por-clube': 'points-per-club',
  'pior-goleiro': 'worst-goalkeeper'
}

export const HIGHLIGHT_TO_PARAM: Record<string, string> = {
  'artillery': 'artilharia',
  'best-away-player': 'melhor-jogador-fora',
  'best-bench': 'melhor-banco',
  'best-coach': 'melhor-tecnico',
  'best-home-player': 'melhor-jogador-em-casa',
  'defense-efficiency': 'eficiencia-defensiva',
  'finish-efficiency': 'eficiencia-de-finalizacao',
  'highest-average': 'maior-media',
  'highest-scorer': 'maior-pontuacao',
  'highest-finisher': 'mais-finalizacoes',
  'least-valued-player': 'menos-valorizado',
  'lineups-per-club': 'escalacoes-por-clube',
  'more-assists': 'mais-assistencias',
  'more-defenses': 'mais-defesas',
  'more-red-cards': 'mais-cartoes-vermelhos',
  'more-tackles': 'mais-desarmes',
  'more-yellow-cards': 'mais-cartoes-amarelos',
  'most-offsided-player': 'mais-impedido',
  'most-rounds-as-captain': 'mais-rodadas-como-capitao',
  'most-scheduled-player': 'mais-escalado',
  'most-valued-player': 'mais-valorizado',
  'points-per-club': 'pontos-por-clube',
  'worst-goalkeeper': 'pior-goleiro'
}
